2022-06-06 17:08:27,283 INFO    MainThread:28148 [wandb_setup.py:_flush():76] Loading settings from C:\Users\nicol\.config\wandb\settings
2022-06-06 17:08:27,283 INFO    MainThread:28148 [wandb_setup.py:_flush():76] Loading settings from C:\Users\nicol\Documents\Academics\Spring2022\TCSS556\KGAT-pytorch\wandb\settings
2022-06-06 17:08:27,283 INFO    MainThread:28148 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-06 17:08:27,283 INFO    MainThread:28148 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-06-06 17:08:27,284 INFO    MainThread:28148 [wandb_init.py:_log_setup():428] Logging user logs to C:\Users\nicol\Documents\Academics\Spring2022\TCSS556\KGAT-pytorch\wandb\run-20220606_170827-n7ybe8ts\logs\debug.log
2022-06-06 17:08:27,285 INFO    MainThread:28148 [wandb_init.py:_log_setup():429] Logging internal logs to C:\Users\nicol\Documents\Academics\Spring2022\TCSS556\KGAT-pytorch\wandb\run-20220606_170827-n7ybe8ts\logs\debug-internal.log
2022-06-06 17:08:27,285 INFO    MainThread:28148 [wandb_init.py:init():462] calling init triggers
2022-06-06 17:08:27,285 INFO    MainThread:28148 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {}
2022-06-06 17:08:27,285 INFO    MainThread:28148 [wandb_init.py:init():515] starting backend
2022-06-06 17:08:27,285 INFO    MainThread:28148 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-06-06 17:08:27,300 INFO    MainThread:28148 [backend.py:ensure_launched():217] starting backend process...
2022-06-06 17:08:27,370 INFO    MainThread:28148 [backend.py:ensure_launched():222] started backend process with pid: 35592
2022-06-06 17:08:27,371 INFO    MainThread:28148 [wandb_init.py:init():525] backend started and connected
2022-06-06 17:08:27,374 INFO    MainThread:28148 [wandb_init.py:init():596] updated telemetry
2022-06-06 17:08:27,453 INFO    MainThread:28148 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-06-06 17:08:57,455 INFO    MainThread:28148 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-06-06 17:08:57,455 ERROR   MainThread:28148 [wandb_init.py:init():636] backend process timed out
2022-06-06 17:08:57,456 ERROR   MainThread:28148 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-06-06 17:08:57,469 ERROR   MainThread:28148 [wandb_init.py:init():1026] error
Traceback (most recent call last):
  File "C:\Users\nicol\Anaconda3\envs\kgat-pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 999, in init
    run = wi.init()
  File "C:\Users\nicol\Anaconda3\envs\kgat-pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 651, in init
    backend.cleanup()
  File "C:\Users\nicol\Anaconda3\envs\kgat-pytorch\lib\site-packages\wandb\sdk\backend\backend.py", line 246, in cleanup
    self.interface.join()
  File "C:\Users\nicol\Anaconda3\envs\kgat-pytorch\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 475, in join
    super().join()
  File "C:\Users\nicol\Anaconda3\envs\kgat-pytorch\lib\site-packages\wandb\sdk\interface\interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "C:\Users\nicol\Anaconda3\envs\kgat-pytorch\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\nicol\Anaconda3\envs\kgat-pytorch\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\nicol\Anaconda3\envs\kgat-pytorch\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
